# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55074d8935172203fca7d05c73af4cd9a1f81ff20f02dd35d30f05e474b0c0cdadc92e323fc4e95734b928c251aef11e18392c012e1180eef5c3ab689fba6b3d

test:
  secret_key_base: 5e50e26e95805fedc54aaa793eca1c3015181d73a48eb814f6979793d335a279187a3863984a63b97602d7f0da5ef6967e81a992f4136b3689dcc2f9a405e894

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
